mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url 

from . import views 

urlpatterns = [
	# ex: /polls/
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	# ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
'''
	Create a model named Question extended from parent class django.db.models.Model. Question models
	has two field is question_text and pub_date, they are created with some parameter as:
		+ max_length: this is specify length of field, this is used in validation.
		+ 'date published': Used to define a human-readable name for a field. And other field not specify
			human- readable name, django will auto assign a machine-readable name. and a tiny note:
			It always take the first position in parameters list
	Every fields is belong about one type of field was defined in django.db.models. As we see we 
	have some field type as: CharField, DateTimeField, IntegerField and a special field is ForeignKey
	was used in question field on Choice mode: this tell django each Choice is related to a single 
	Question. And django support popular relate type: many-to-many, many-to-one, one-to-one.
'''
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published', default=timezone.now)

	# __unicode__(__str__ on python 3): return unicode value
	def __unicode__(self): 
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	# Improve display possible of was_published_recently on admin
	### admin_order_field not work if change to 'question_text' or commented: 
	### i am not yet understand, perhap cause is
	### in admin.py we indicated order to display in option list_display
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Question

# Create your views here.
def index(request):
	# get 5 questions latest
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list}
	return render(request, 'polls/index.html', context)

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
	response = "You're looking at the results of question %s."
	return HttpResponse(response % question_id)	

def vote(request, question_id):
	return HttpResponse("You're voteing on question %s." % question_id)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
	{% endfor %}
	<input type="submit" value="vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
	{% for question in latest_question_list %}
		{# <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> #}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
</ul>
{% else %}
	<p>No polls available.</p>
{% endif %}